# Generated by Django 5.2.14 on 2026-05-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_code", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("ready", "Ready"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                ("current_section_index", models.PositiveIntegerField(default=0)),
                ("consent_confirmed", models.BooleanField(default=False)),
                ("transcript_saved", models.BooleanField(default=False)),
                ("summary_generated", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision requested"),
                            ("not_usable", "Not usable"),
                        ],
                        default="not_reviewed",
                        max_length=30,
                    ),
                ),
                (
                    "output_quality_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("waiting", "Waiting"),
                            ("summary_generated", "Summary generated"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision requested"),
                            ("not_usable", "Not usable"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("stakeholder_group", models.CharField(max_length=100)),
                ("purpose", models.TextField()),
                (
                    "interview_mode",
                    models.CharField(
                        default="AI-led semi-structured interview", max_length=100
                    ),
                ),
                (
                    "estimated_duration",
                    models.CharField(default="10–15 minutes", max_length=50),
                ),
                (
                    "output_description",
                    models.CharField(
                        default="Transcript + structured summary", max_length=200
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=list)),
                ("ethics_rules", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("participant", "Participant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("section", models.CharField(blank=True, max_length=100)),
                ("section_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="interviews.protocol",
            ),
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_grounded_in_transcript", models.BooleanField(default=False)),
                ("no_unsupported_interpretation", models.BooleanField(default=False)),
                ("no_medical_or_diagnostic_advice", models.BooleanField(default=False)),
                ("participant_safety_respected", models.BooleanField(default=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision requested"),
                            ("not_usable", "Not usable"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decision",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.CharField(max_length=20, unique=True)),
                ("stakeholder_group", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("not_started", "Not started"),
                        ],
                        default="ready",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stakeholders",
                        to="interviews.protocol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="stakeholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="interviews.stakeholder",
            ),
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.TextField(blank=True)),
                ("main_triggers", models.TextField(blank=True)),
                ("participant_response", models.TextField(blank=True)),
                ("potential_support_need", models.TextField(blank=True)),
                ("support_concept_reaction", models.TextField(blank=True)),
                ("public_use_concerns", models.TextField(blank=True)),
                ("missing_information_flags", models.TextField(blank=True)),
                ("edited_by_researcher", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
        ),
    ]
