# Generated by Django 5.2.14 on 2026-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="researcher_note",
            field=models.TextField(blank=True),
        ),
    ]
