# Generated by Django 5.2.14 on 2026-05-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_interviewsession_researcher_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("section_index", models.PositiveIntegerField(default=0)),
                (
                    "answer_status",
                    models.CharField(
                        choices=[
                            ("sufficient", "Sufficient"),
                            ("partial", "Partial"),
                            ("vague", "Vague"),
                            ("too_short", "Too short"),
                            ("off_topic", "Off topic"),
                            ("skipped", "Skipped"),
                            ("stopped", "Stopped"),
                            ("safety_boundary", "Safety boundary"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ask_follow_up", "Ask follow-up"),
                            ("move_next", "Move next"),
                            (
                                "flag_missing_and_move_next",
                                "Flag missing and move next",
                            ),
                            ("skip", "Skip"),
                            ("stop", "Stop"),
                            ("boundary_response", "Boundary response"),
                            ("complete", "Complete"),
                        ],
                        max_length=50,
                    ),
                ),
                ("probe_count_before", models.PositiveIntegerField(default=0)),
                ("missing_information", models.JSONField(blank=True, default=list)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_decisions",
                        to="interviews.message",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_decisions",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
