# Generated by Django 5.2.14 on 2026-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0003_agentdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdecision",
            name="limitations_and_missing_information_visible",
            field=models.BooleanField(default=False),
        ),
    ]
